trigger:
  paths:
    include:
    - vote/*
resources:
  repositories:
  - repository: self
variables:
- name: dockerRegistryServiceConnection
  value: '57e414e0-47cb-4e57-bbd5-bf35a9b189da'
- name: imageRepository
  value: 'votingapp'
- name: containerRegistry
  value: 'vibithaaazurecicd.azurecr.io'
- name: dockerfilePath
  value: '$(Build.SourcesDirectory)/result/Dockerfile'
- name: tag
  value: '$(Build.BuildId)'
pool:
  name: 'azureagent'
stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build an image to container registry
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: 'vote/Dockerfile'
        tags: '$(tag)'
- stage: Push
  displayName: Push stage
  jobs:
  - job: Push
    displayName: Push
    steps:
    - task: Docker@2
      displayName: push an image to container registry
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'push'
        Dockerfile: 'vote/Dockerfile'
        tags: '$(tag)'

